/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/stage/stage.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export default function Stage(props) {
  const { nodes, materials } = useGLTF("/models/stage/stage.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.ground.geometry}
        material={materials["white-mat"]}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes["milk-pourer"].geometry}
        material={materials["white-mat"]}
        position={[-1.647, 1.78, 0]}
        castShadow
        receiveShadow
      />

      <RigidBody
        type="fixed"
        colliders="trimesh"
        restitution={0.7}
        friction={0.25}
      >
        <mesh
          geometry={nodes["cereal-bowl"].geometry}
          material={materials["white-mat"]}
          castShadow
          receiveShadow
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/models/stage/stage.glb");
